import {unlock,sfx,toggleMute,isMuted} from './audio.js';
import {validSnapshot} from './security.js';
const root=document.querySelector('#game');const origin=location.origin;const sdk=ClassroomGameSDK.create({parentOrigin:origin});let current=null,online=true,locked=false,startedAt=0,lastQuestion='',lastResult='',hitDone=false,lastRound='',announcedEnd='';let loadedQuestions=[];
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const send=(type,payload)=>parent.postMessage({channel:'mouse-adapter-v1',type,payload},origin);
function waiting(title,message){root.innerHTML=`<section class="waiting-scene"><img src="assets/mouse.png" alt="Chú chuột trong khu vườn"><h2>${esc(title)}</h2><p>${esc(message)}</p></section>`}
function render(s){
 if(s.roundId!==lastRound){lastRound=s.roundId;lastQuestion='';lastResult='';announcedEnd=''}current=s;
 if(s.status==='lobby'){waiting('Khu vườn đã sẵn sàng!','Đợi giáo viên bắt đầu. Chọn đúng đáp án để nhận búa và đập chuột nhé.');return}
 if(s.status==='ended'){waiting('Hoàn thành chuyến đi săn!',`Bạn được ${s.me.score} điểm, đập trúng ${s.me.correct} chú chuột. Xem bảng xếp hạng của cả lớp ở bên ngoài.`);if(announcedEnd!==s.roundId){announcedEnd=s.roundId;sfx('win');sdk.send({type:'gameEnd',payload:{roomCode:s.roomCode,leaderboard:s.leaderboard}})}return}
 if(!s.question){waiting('Bạn đã hoàn thành!','Chờ các bạn còn lại. Điểm của bạn đã được lưu.');return}
 const q=loadedQuestions.find(q=>q.id===s.question.id)||s.question,pending=s.me.pending;
 if(lastQuestion===q.id){if(pending&&lastResult!==q.id)showResult(pending);return}
 lastQuestion=q.id;lastResult='';locked=false;hitDone=false;startedAt=performance.now();
 root.innerHTML=`<section class="game-stage"><div class="game-top"><strong>🌱 Khu vườn tinh anh</strong><span class="pill">Câu ${s.me.done??s.me.index+1} / ${s.total}</span><button id="sound" class="secondary small" aria-label="Bật hoặc tắt âm thanh">${isMuted()?'Âm thanh: tắt':'Âm thanh: bật'}</button></div><div class="progress-track"><div style="width:${s.me.index/s.total*100}%"></div></div><div class="question-area"><div class="question-label">ĐỌC KỸ · CHỌN MỘT ĐÁP ÁN</div><h2>${esc(q.prompt)}</h2><div class="option-grid">${q.options.map((o,i)=>`<button class="option" data-answer="${esc(o.id)}"><span class="letter">${'ABCD'[i]}</span><span>${esc(o.text)}</span></button>`).join('')}</div></div><div class="garden"><img class="side-hole" src="assets/hole.png" alt=""><img class="side-hole right" src="assets/hole.png" alt=""><span class="grass" aria-hidden="true">🌿</span><span class="grass right" aria-hidden="true">🌿</span><span class="flower" aria-hidden="true">🌼</span><div id="callout" class="hit-callout">Bạn có bắt được mình không?</div><div class="mole-slot"><img class="hole" src="assets/hole.png" alt=""><div class="mouse-window"><button class="mouse-target" id="mouse" aria-label="Đập chuột" disabled><img src="assets/mouse.png" alt="Chú chuột"></button></div><img class="mallet" id="mallet" src="assets/hammer.png" alt=""></div></div><div class="feedback" role="status" aria-live="polite"><p id="feedback-text">Chọn đúng để nhận một lượt đập chuột.</p><button id="next" class="small gold hide">Sang câu tiếp theo →</button></div></section>`;
 root.querySelector('#sound').onclick=e=>{unlock();toggleMute();e.currentTarget.textContent=isMuted()?'Âm thanh: tắt':'Âm thanh: bật'};
 root.querySelectorAll('[data-answer]').forEach(b=>b.onclick=()=>{unlock();if(locked||!online)return;locked=true;sfx('tap');b.classList.add('selected');root.querySelectorAll('[data-answer]').forEach(x=>x.disabled=true);root.querySelector('#feedback-text').textContent='Đang kiểm tra đáp án…';send('answerAttempt',{questionId:q.id,answer:b.dataset.answer,timeMs:performance.now()-startedAt})});
 root.querySelector('#mouse').onclick=()=>{if(!pendingResult()?.isCorrect||hitDone||!online)return;unlock();hitDone=true;sfx('hit');root.querySelector('#mouse').className='mouse-target hit';root.querySelector('#mouse').disabled=true;root.querySelector('#mallet').classList.add('swing');root.querySelector('#callout').textContent='Đập trúng rồi! +10 điểm';const burst=document.createElement('div');burst.className='burst';burst.textContent='✦';root.querySelector('.garden').append(burst);root.querySelector('#feedback-text').innerHTML='<strong>Giỏi lắm! Bạn đã bắt được chuột.</strong>';root.querySelector('#next').classList.remove('hide')};
 root.querySelector('#next').onclick=()=>{if(!online)return;unlock();root.querySelector('#next').disabled=true;send('advance',{questionId:q.id})};
 if(pending)showResult(pending);else sfx('pop');updatePresence();
}
const pendingResult=()=>current?.me?.pending;
function showResult(r){lastResult=r.questionId;locked=true;const buttons=root.querySelectorAll('[data-answer]');buttons.forEach(b=>{b.disabled=true;b.classList.toggle('correct',b.dataset.answer===r.correctOptionId);if(b.dataset.answer===r.answer&&!r.isCorrect)b.classList.add('wrong')});
 sdk.send({type:'submitAnswer',payload:{playerId:current.me.playerId,questionId:r.questionId,answer:r.answer,isCorrect:r.isCorrect,timeMs:r.timeMs}});sdk.send({type:'updateScore',payload:{playerId:current.me.playerId,score:r.score,delta:r.delta}});
 if(r.isCorrect){sfx('correct');root.querySelector('#feedback-text').innerHTML='<strong>Chính xác! +10 điểm.</strong> Bấm vào chú chuột để đập!';root.querySelector('#callout').textContent='Bấm vào chuột!';root.querySelector('#mouse').disabled=!online;root.querySelector('#mouse').classList.add('ready')}
 else{sfx('miss');root.querySelector('#feedback-text').textContent=`Chuột trốn mất rồi! Đáp án đúng: ${r.correctText}. Cố gắng ở câu tiếp theo nhé.`;root.querySelector('#callout').textContent='Hẹn gặp lại ở câu sau!';root.querySelector('#mouse').classList.add('away');root.querySelector('#next').classList.remove('hide')}
}
function updatePresence(){if(!current||current.status!=='playing')return;root.querySelectorAll('[data-answer]').forEach(b=>b.disabled=locked||!online);const mouse=root.querySelector('#mouse');if(mouse)mouse.disabled=!online||!pendingResult()?.isCorrect||hitDone;const next=root.querySelector('#next');if(next)next.disabled=!online;}
addEventListener('message',e=>{if(e.origin!==origin||e.source!==parent||e.data?.channel!=='mouse-adapter-v1')return;if(e.data.type==='snapshot'&&validSnapshot(e.data.payload))render(e.data.payload);if(e.data.type==='presence'&&typeof e.data.payload?.online==='boolean'){online=e.data.payload.online;updatePresence()}});
sdk.onMessage(m=>{if(m.type==='loadContent')loadedQuestions=m.payload.questions;if(m.type==='endGame'&&current){render({...current,status:'ended'})}});
waiting('Xin chào, thợ săn chuột!','Đang kết nối với lớp học…');sdk.send({type:'gameReady',payload:{gameId:'dap-chuot-mcq',version:'1.0.0'}});
